
sudo: required
services:
  - docker
language: python

env:
  - IMGTAG=debian8
  - IMGTAG=debian9
  - IMGTAG=fedora27
  - IMGTAG=fedora28
  - IMGTAG=ubuntu16.04
  - IMGTAG=ubuntu18.04

before_install:
- docker pull exaile/exaile-testimg:${IMGTAG}

script:
- docker run --rm -it -e HOME=/home -v $(pwd):/app -w /app exaile/exaile-testimg:${IMGTAG} make BUILDDIR=/tmp test test_compile check-doc

jobs:
  include:
  - stage: format-check
    sudo: false
    language: python
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - make check_format

notifications:
  irc:
    channels:
    - "chat.freenode.net#exaile"
    use_notice: true
    skip_join: true
    on_success: change
